/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllianceRouteImport } from './routes/alliance'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SemiCallbackRouteImport } from './routes/semi-callback'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as AllianceIndexRouteImport } from './routes/alliance.index'
import { Route as AllianceDocumentsRouteImport } from './routes/alliance.documents'
import { Route as AllianceNodesRouteImport } from './routes/alliance.nodes'
import { Route as EventsEventIdRouteImport } from './routes/events_.$eventId'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as MeEventsRouteImport } from './routes/me.events'
import { Route as MeGrainsRouteImport } from './routes/me.grains'
import { Route as MeIdentityRouteImport } from './routes/me.identity'
import { Route as MePostsRouteImport } from './routes/me.posts'
import { Route as MeSettingsRouteImport } from './routes/me.settings'
import { Route as MeTasksRouteImport } from './routes/me.tasks'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as ProfileActorRouteImport } from './routes/profile.$actor'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as AllianceAnnouncementsIdRouteImport } from './routes/alliance.announcements.$id'
import { Route as AllianceProposalsIdRouteImport } from './routes/alliance.proposals.$id'
import { Route as MeGrainsReceiveRouteImport } from './routes/me.grains_.receive'
import { Route as MeGrainsSendRouteImport } from './routes/me.grains_.send'
import { Route as MeSettingsIndexRouteImport } from './routes/me.settings.index'
import { Route as MeSettingsAccountRouteImport } from './routes/me.settings.account'
import { Route as MeSettingsProfileRouteImport } from './routes/me.settings.profile'
import { Route as NodesNodeIdEventsRouteImport } from './routes/nodes_.$nodeId.events'
import { Route as NodesNodeIdGrainsRouteImport } from './routes/nodes_.$nodeId.grains'
import { Route as NodesNodeIdTasksRouteImport } from './routes/nodes_.$nodeId.tasks'
import { Route as ProfileActorIndexRouteImport } from './routes/profile.$actor.index'
import { Route as ProfileActorFollowersRouteImport } from './routes/profile.$actor.followers'
import { Route as ProfileActorFollowingRouteImport } from './routes/profile.$actor.following'
import { Route as MeGrainsSendScanRouteImport } from './routes/me.grains_.send.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllianceRoute = AllianceRouteImport.update({
  id: '/alliance',
  path: '/alliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SemiCallbackRoute = SemiCallbackRouteImport.update({
  id: '/semi-callback',
  path: '/semi-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AllianceIndexRoute = AllianceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AllianceRoute,
} as any)
const AllianceDocumentsRoute = AllianceDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AllianceRoute,
} as any)
const AllianceNodesRoute = AllianceNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AllianceRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const MeEventsRoute = MeEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => MeRoute,
} as any)
const MeGrainsRoute = MeGrainsRouteImport.update({
  id: '/grains',
  path: '/grains',
  getParentRoute: () => MeRoute,
} as any)
const MeIdentityRoute = MeIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => MeRoute,
} as any)
const MePostsRoute = MePostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => MeRoute,
} as any)
const MeSettingsRoute = MeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MeRoute,
} as any)
const MeTasksRoute = MeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => MeRoute,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileActorRoute = ProfileActorRouteImport.update({
  id: '/profile/$actor',
  path: '/profile/$actor',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TasksRoute,
} as any)
const AllianceAnnouncementsIdRoute = AllianceAnnouncementsIdRouteImport.update({
  id: '/announcements/$id',
  path: '/announcements/$id',
  getParentRoute: () => AllianceRoute,
} as any)
const AllianceProposalsIdRoute = AllianceProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => AllianceRoute,
} as any)
const MeGrainsReceiveRoute = MeGrainsReceiveRouteImport.update({
  id: '/grains_/receive',
  path: '/grains/receive',
  getParentRoute: () => MeRoute,
} as any)
const MeGrainsSendRoute = MeGrainsSendRouteImport.update({
  id: '/grains_/send',
  path: '/grains/send',
  getParentRoute: () => MeRoute,
} as any)
const MeSettingsIndexRoute = MeSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeSettingsRoute,
} as any)
const MeSettingsAccountRoute = MeSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MeSettingsRoute,
} as any)
const MeSettingsProfileRoute = MeSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MeSettingsRoute,
} as any)
const NodesNodeIdEventsRoute = NodesNodeIdEventsRouteImport.update({
  id: '/nodes_/$nodeId/events',
  path: '/nodes/$nodeId/events',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdGrainsRoute = NodesNodeIdGrainsRouteImport.update({
  id: '/nodes_/$nodeId/grains',
  path: '/nodes/$nodeId/grains',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdTasksRoute = NodesNodeIdTasksRouteImport.update({
  id: '/nodes_/$nodeId/tasks',
  path: '/nodes/$nodeId/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileActorIndexRoute = ProfileActorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileActorRoute,
} as any)
const ProfileActorFollowersRoute = ProfileActorFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => ProfileActorRoute,
} as any)
const ProfileActorFollowingRoute = ProfileActorFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => ProfileActorRoute,
} as any)
const MeGrainsSendScanRoute = MeGrainsSendScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => MeGrainsSendRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alliance': typeof AllianceRouteWithChildren
  '/compose': typeof ComposeRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/semi-callback': typeof SemiCallbackRoute
  '/tasks': typeof TasksRouteWithChildren
  '/alliance/documents': typeof AllianceDocumentsRoute
  '/alliance/nodes': typeof AllianceNodesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/me/events': typeof MeEventsRoute
  '/me/grains': typeof MeGrainsRoute
  '/me/identity': typeof MeIdentityRoute
  '/me/posts': typeof MePostsRoute
  '/me/settings': typeof MeSettingsRouteWithChildren
  '/me/tasks': typeof MeTasksRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/profile/$actor': typeof ProfileActorRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/alliance/': typeof AllianceIndexRoute
  '/me/': typeof MeIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/alliance/announcements/$id': typeof AllianceAnnouncementsIdRoute
  '/alliance/proposals/$id': typeof AllianceProposalsIdRoute
  '/me/grains/receive': typeof MeGrainsReceiveRoute
  '/me/grains/send': typeof MeGrainsSendRouteWithChildren
  '/me/settings/account': typeof MeSettingsAccountRoute
  '/me/settings/profile': typeof MeSettingsProfileRoute
  '/nodes/$nodeId/events': typeof NodesNodeIdEventsRoute
  '/nodes/$nodeId/grains': typeof NodesNodeIdGrainsRoute
  '/nodes/$nodeId/tasks': typeof NodesNodeIdTasksRoute
  '/profile/$actor/followers': typeof ProfileActorFollowersRoute
  '/profile/$actor/following': typeof ProfileActorFollowingRoute
  '/me/settings/': typeof MeSettingsIndexRoute
  '/profile/$actor/': typeof ProfileActorIndexRoute
  '/me/grains/send/scan': typeof MeGrainsSendScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/semi-callback': typeof SemiCallbackRoute
  '/alliance/documents': typeof AllianceDocumentsRoute
  '/alliance/nodes': typeof AllianceNodesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/me/events': typeof MeEventsRoute
  '/me/grains': typeof MeGrainsRoute
  '/me/identity': typeof MeIdentityRoute
  '/me/posts': typeof MePostsRoute
  '/me/tasks': typeof MeTasksRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/alliance': typeof AllianceIndexRoute
  '/me': typeof MeIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/alliance/announcements/$id': typeof AllianceAnnouncementsIdRoute
  '/alliance/proposals/$id': typeof AllianceProposalsIdRoute
  '/me/grains/receive': typeof MeGrainsReceiveRoute
  '/me/grains/send': typeof MeGrainsSendRouteWithChildren
  '/me/settings/account': typeof MeSettingsAccountRoute
  '/me/settings/profile': typeof MeSettingsProfileRoute
  '/nodes/$nodeId/events': typeof NodesNodeIdEventsRoute
  '/nodes/$nodeId/grains': typeof NodesNodeIdGrainsRoute
  '/nodes/$nodeId/tasks': typeof NodesNodeIdTasksRoute
  '/profile/$actor/followers': typeof ProfileActorFollowersRoute
  '/profile/$actor/following': typeof ProfileActorFollowingRoute
  '/me/settings': typeof MeSettingsIndexRoute
  '/profile/$actor': typeof ProfileActorIndexRoute
  '/me/grains/send/scan': typeof MeGrainsSendScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alliance': typeof AllianceRouteWithChildren
  '/compose': typeof ComposeRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/posts': typeof PostsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/semi-callback': typeof SemiCallbackRoute
  '/tasks': typeof TasksRouteWithChildren
  '/alliance/documents': typeof AllianceDocumentsRoute
  '/alliance/nodes': typeof AllianceNodesRoute
  '/events_/$eventId': typeof EventsEventIdRoute
  '/me/events': typeof MeEventsRoute
  '/me/grains': typeof MeGrainsRoute
  '/me/identity': typeof MeIdentityRoute
  '/me/posts': typeof MePostsRoute
  '/me/settings': typeof MeSettingsRouteWithChildren
  '/me/tasks': typeof MeTasksRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/profile/$actor': typeof ProfileActorRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/alliance/': typeof AllianceIndexRoute
  '/me/': typeof MeIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/alliance/announcements/$id': typeof AllianceAnnouncementsIdRoute
  '/alliance/proposals/$id': typeof AllianceProposalsIdRoute
  '/me/grains_/receive': typeof MeGrainsReceiveRoute
  '/me/grains_/send': typeof MeGrainsSendRouteWithChildren
  '/me/settings/account': typeof MeSettingsAccountRoute
  '/me/settings/profile': typeof MeSettingsProfileRoute
  '/nodes_/$nodeId/events': typeof NodesNodeIdEventsRoute
  '/nodes_/$nodeId/grains': typeof NodesNodeIdGrainsRoute
  '/nodes_/$nodeId/tasks': typeof NodesNodeIdTasksRoute
  '/profile/$actor/followers': typeof ProfileActorFollowersRoute
  '/profile/$actor/following': typeof ProfileActorFollowingRoute
  '/me/settings/': typeof MeSettingsIndexRoute
  '/profile/$actor/': typeof ProfileActorIndexRoute
  '/me/grains_/send/scan': typeof MeGrainsSendScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alliance'
    | '/compose'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/notifications'
    | '/posts'
    | '/register'
    | '/search'
    | '/semi-callback'
    | '/tasks'
    | '/alliance/documents'
    | '/alliance/nodes'
    | '/events/$eventId'
    | '/me/events'
    | '/me/grains'
    | '/me/identity'
    | '/me/posts'
    | '/me/settings'
    | '/me/tasks'
    | '/nodes/$nodeId'
    | '/profile/$actor'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/alliance/'
    | '/me/'
    | '/tasks/'
    | '/alliance/announcements/$id'
    | '/alliance/proposals/$id'
    | '/me/grains/receive'
    | '/me/grains/send'
    | '/me/settings/account'
    | '/me/settings/profile'
    | '/nodes/$nodeId/events'
    | '/nodes/$nodeId/grains'
    | '/nodes/$nodeId/tasks'
    | '/profile/$actor/followers'
    | '/profile/$actor/following'
    | '/me/settings/'
    | '/profile/$actor/'
    | '/me/grains/send/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compose'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/posts'
    | '/register'
    | '/search'
    | '/semi-callback'
    | '/alliance/documents'
    | '/alliance/nodes'
    | '/events/$eventId'
    | '/me/events'
    | '/me/grains'
    | '/me/identity'
    | '/me/posts'
    | '/me/tasks'
    | '/nodes/$nodeId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/alliance'
    | '/me'
    | '/tasks'
    | '/alliance/announcements/$id'
    | '/alliance/proposals/$id'
    | '/me/grains/receive'
    | '/me/grains/send'
    | '/me/settings/account'
    | '/me/settings/profile'
    | '/nodes/$nodeId/events'
    | '/nodes/$nodeId/grains'
    | '/nodes/$nodeId/tasks'
    | '/profile/$actor/followers'
    | '/profile/$actor/following'
    | '/me/settings'
    | '/profile/$actor'
    | '/me/grains/send/scan'
  id:
    | '__root__'
    | '/'
    | '/alliance'
    | '/compose'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/notifications'
    | '/posts'
    | '/register'
    | '/search'
    | '/semi-callback'
    | '/tasks'
    | '/alliance/documents'
    | '/alliance/nodes'
    | '/events_/$eventId'
    | '/me/events'
    | '/me/grains'
    | '/me/identity'
    | '/me/posts'
    | '/me/settings'
    | '/me/tasks'
    | '/nodes/$nodeId'
    | '/profile/$actor'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/alliance/'
    | '/me/'
    | '/tasks/'
    | '/alliance/announcements/$id'
    | '/alliance/proposals/$id'
    | '/me/grains_/receive'
    | '/me/grains_/send'
    | '/me/settings/account'
    | '/me/settings/profile'
    | '/nodes_/$nodeId/events'
    | '/nodes_/$nodeId/grains'
    | '/nodes_/$nodeId/tasks'
    | '/profile/$actor/followers'
    | '/profile/$actor/following'
    | '/me/settings/'
    | '/profile/$actor/'
    | '/me/grains_/send/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllianceRoute: typeof AllianceRouteWithChildren
  ComposeRoute: typeof ComposeRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PostsRoute: typeof PostsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SemiCallbackRoute: typeof SemiCallbackRoute
  TasksRoute: typeof TasksRouteWithChildren
  EventsEventIdRoute: typeof EventsEventIdRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  ProfileActorRoute: typeof ProfileActorRouteWithChildren
  NodesNodeIdEventsRoute: typeof NodesNodeIdEventsRoute
  NodesNodeIdGrainsRoute: typeof NodesNodeIdGrainsRoute
  NodesNodeIdTasksRoute: typeof NodesNodeIdTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alliance': {
      id: '/alliance'
      path: '/alliance'
      fullPath: '/alliance'
      preLoaderRoute: typeof AllianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semi-callback': {
      id: '/semi-callback'
      path: '/semi-callback'
      fullPath: '/semi-callback'
      preLoaderRoute: typeof SemiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alliance/': {
      id: '/alliance/'
      path: '/'
      fullPath: '/alliance/'
      preLoaderRoute: typeof AllianceIndexRouteImport
      parentRoute: typeof AllianceRoute
    }
    '/alliance/documents': {
      id: '/alliance/documents'
      path: '/documents'
      fullPath: '/alliance/documents'
      preLoaderRoute: typeof AllianceDocumentsRouteImport
      parentRoute: typeof AllianceRoute
    }
    '/alliance/nodes': {
      id: '/alliance/nodes'
      path: '/nodes'
      fullPath: '/alliance/nodes'
      preLoaderRoute: typeof AllianceNodesRouteImport
      parentRoute: typeof AllianceRoute
    }
    '/events_/$eventId': {
      id: '/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/events': {
      id: '/me/events'
      path: '/events'
      fullPath: '/me/events'
      preLoaderRoute: typeof MeEventsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/grains': {
      id: '/me/grains'
      path: '/grains'
      fullPath: '/me/grains'
      preLoaderRoute: typeof MeGrainsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/identity': {
      id: '/me/identity'
      path: '/identity'
      fullPath: '/me/identity'
      preLoaderRoute: typeof MeIdentityRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/posts': {
      id: '/me/posts'
      path: '/posts'
      fullPath: '/me/posts'
      preLoaderRoute: typeof MePostsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/settings': {
      id: '/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof MeSettingsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/tasks': {
      id: '/me/tasks'
      path: '/tasks'
      fullPath: '/me/tasks'
      preLoaderRoute: typeof MeTasksRouteImport
      parentRoute: typeof MeRoute
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$actor': {
      id: '/profile/$actor'
      path: '/profile/$actor'
      fullPath: '/profile/$actor'
      preLoaderRoute: typeof ProfileActorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof TasksRoute
    }
    '/alliance/announcements/$id': {
      id: '/alliance/announcements/$id'
      path: '/announcements/$id'
      fullPath: '/alliance/announcements/$id'
      preLoaderRoute: typeof AllianceAnnouncementsIdRouteImport
      parentRoute: typeof AllianceRoute
    }
    '/alliance/proposals/$id': {
      id: '/alliance/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/alliance/proposals/$id'
      preLoaderRoute: typeof AllianceProposalsIdRouteImport
      parentRoute: typeof AllianceRoute
    }
    '/me/grains_/receive': {
      id: '/me/grains_/receive'
      path: '/grains/receive'
      fullPath: '/me/grains/receive'
      preLoaderRoute: typeof MeGrainsReceiveRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/grains_/send': {
      id: '/me/grains_/send'
      path: '/grains/send'
      fullPath: '/me/grains/send'
      preLoaderRoute: typeof MeGrainsSendRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/settings/': {
      id: '/me/settings/'
      path: '/'
      fullPath: '/me/settings/'
      preLoaderRoute: typeof MeSettingsIndexRouteImport
      parentRoute: typeof MeSettingsRoute
    }
    '/me/settings/account': {
      id: '/me/settings/account'
      path: '/account'
      fullPath: '/me/settings/account'
      preLoaderRoute: typeof MeSettingsAccountRouteImport
      parentRoute: typeof MeSettingsRoute
    }
    '/me/settings/profile': {
      id: '/me/settings/profile'
      path: '/profile'
      fullPath: '/me/settings/profile'
      preLoaderRoute: typeof MeSettingsProfileRouteImport
      parentRoute: typeof MeSettingsRoute
    }
    '/nodes_/$nodeId/events': {
      id: '/nodes_/$nodeId/events'
      path: '/nodes/$nodeId/events'
      fullPath: '/nodes/$nodeId/events'
      preLoaderRoute: typeof NodesNodeIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes_/$nodeId/grains': {
      id: '/nodes_/$nodeId/grains'
      path: '/nodes/$nodeId/grains'
      fullPath: '/nodes/$nodeId/grains'
      preLoaderRoute: typeof NodesNodeIdGrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes_/$nodeId/tasks': {
      id: '/nodes_/$nodeId/tasks'
      path: '/nodes/$nodeId/tasks'
      fullPath: '/nodes/$nodeId/tasks'
      preLoaderRoute: typeof NodesNodeIdTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$actor/': {
      id: '/profile/$actor/'
      path: '/'
      fullPath: '/profile/$actor/'
      preLoaderRoute: typeof ProfileActorIndexRouteImport
      parentRoute: typeof ProfileActorRoute
    }
    '/profile/$actor/followers': {
      id: '/profile/$actor/followers'
      path: '/followers'
      fullPath: '/profile/$actor/followers'
      preLoaderRoute: typeof ProfileActorFollowersRouteImport
      parentRoute: typeof ProfileActorRoute
    }
    '/profile/$actor/following': {
      id: '/profile/$actor/following'
      path: '/following'
      fullPath: '/profile/$actor/following'
      preLoaderRoute: typeof ProfileActorFollowingRouteImport
      parentRoute: typeof ProfileActorRoute
    }
    '/me/grains_/send/scan': {
      id: '/me/grains_/send/scan'
      path: '/scan'
      fullPath: '/me/grains/send/scan'
      preLoaderRoute: typeof MeGrainsSendScanRouteImport
      parentRoute: typeof MeGrainsSendRoute
    }
  }
}

interface AllianceRouteChildren {
  AllianceDocumentsRoute: typeof AllianceDocumentsRoute
  AllianceNodesRoute: typeof AllianceNodesRoute
  AllianceIndexRoute: typeof AllianceIndexRoute
  AllianceAnnouncementsIdRoute: typeof AllianceAnnouncementsIdRoute
  AllianceProposalsIdRoute: typeof AllianceProposalsIdRoute
}

const AllianceRouteChildren: AllianceRouteChildren = {
  AllianceDocumentsRoute: AllianceDocumentsRoute,
  AllianceNodesRoute: AllianceNodesRoute,
  AllianceIndexRoute: AllianceIndexRoute,
  AllianceAnnouncementsIdRoute: AllianceAnnouncementsIdRoute,
  AllianceProposalsIdRoute: AllianceProposalsIdRoute,
}

const AllianceRouteWithChildren = AllianceRoute._addFileChildren(
  AllianceRouteChildren,
)

interface MeSettingsRouteChildren {
  MeSettingsAccountRoute: typeof MeSettingsAccountRoute
  MeSettingsProfileRoute: typeof MeSettingsProfileRoute
  MeSettingsIndexRoute: typeof MeSettingsIndexRoute
}

const MeSettingsRouteChildren: MeSettingsRouteChildren = {
  MeSettingsAccountRoute: MeSettingsAccountRoute,
  MeSettingsProfileRoute: MeSettingsProfileRoute,
  MeSettingsIndexRoute: MeSettingsIndexRoute,
}

const MeSettingsRouteWithChildren = MeSettingsRoute._addFileChildren(
  MeSettingsRouteChildren,
)

interface MeGrainsSendRouteChildren {
  MeGrainsSendScanRoute: typeof MeGrainsSendScanRoute
}

const MeGrainsSendRouteChildren: MeGrainsSendRouteChildren = {
  MeGrainsSendScanRoute: MeGrainsSendScanRoute,
}

const MeGrainsSendRouteWithChildren = MeGrainsSendRoute._addFileChildren(
  MeGrainsSendRouteChildren,
)

interface MeRouteChildren {
  MeEventsRoute: typeof MeEventsRoute
  MeGrainsRoute: typeof MeGrainsRoute
  MeIdentityRoute: typeof MeIdentityRoute
  MePostsRoute: typeof MePostsRoute
  MeSettingsRoute: typeof MeSettingsRouteWithChildren
  MeTasksRoute: typeof MeTasksRoute
  MeIndexRoute: typeof MeIndexRoute
  MeGrainsReceiveRoute: typeof MeGrainsReceiveRoute
  MeGrainsSendRoute: typeof MeGrainsSendRouteWithChildren
}

const MeRouteChildren: MeRouteChildren = {
  MeEventsRoute: MeEventsRoute,
  MeGrainsRoute: MeGrainsRoute,
  MeIdentityRoute: MeIdentityRoute,
  MePostsRoute: MePostsRoute,
  MeSettingsRoute: MeSettingsRouteWithChildren,
  MeTasksRoute: MeTasksRoute,
  MeIndexRoute: MeIndexRoute,
  MeGrainsReceiveRoute: MeGrainsReceiveRoute,
  MeGrainsSendRoute: MeGrainsSendRouteWithChildren,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksNewRoute: typeof TasksNewRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface ProfileActorRouteChildren {
  ProfileActorFollowersRoute: typeof ProfileActorFollowersRoute
  ProfileActorFollowingRoute: typeof ProfileActorFollowingRoute
  ProfileActorIndexRoute: typeof ProfileActorIndexRoute
}

const ProfileActorRouteChildren: ProfileActorRouteChildren = {
  ProfileActorFollowersRoute: ProfileActorFollowersRoute,
  ProfileActorFollowingRoute: ProfileActorFollowingRoute,
  ProfileActorIndexRoute: ProfileActorIndexRoute,
}

const ProfileActorRouteWithChildren = ProfileActorRoute._addFileChildren(
  ProfileActorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllianceRoute: AllianceRouteWithChildren,
  ComposeRoute: ComposeRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PostsRoute: PostsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SemiCallbackRoute: SemiCallbackRoute,
  TasksRoute: TasksRouteWithChildren,
  EventsEventIdRoute: EventsEventIdRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  ProfileActorRoute: ProfileActorRouteWithChildren,
  NodesNodeIdEventsRoute: NodesNodeIdEventsRoute,
  NodesNodeIdGrainsRoute: NodesNodeIdGrainsRoute,
  NodesNodeIdTasksRoute: NodesNodeIdTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
